[target.riscv32imc-unknown-none-elf]
runner = 'probe-rs run --chip esp32c3 --format idf'
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",

    # "-C",
    # "link-arg=--nmagic",

    # defmt specific
    # "-C",
    # "link-arg=-Tdefmt.x",
]

[build]
target = "riscv32imc-unknown-none-elf"

# might be a bug in compiler, with the effect that flag is unused
[env]
DEFMT_LOG = "trace"
