#[target.riscv32imc-unknown-none-elf]
#[target.riscv32imac-unknown-none-elf]
#
[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]
[build]
target = "riscv32imc-unknown-none-elf.json"

[unstable]
build-std = ["core"]